[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
airdrop_program = "RoQZsTPSQyMVeMfWR2NxCaJD1ui781GE77JJtoz2dw8"

[programs.testnet]
airdrop_program = "RoQZsTPSQyMVeMfWR2NxCaJD1ui781GE77JJtoz2dw8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
